name: env-GI-review
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.7
  - ipykernel = 6.2.0
  - ipywidgets
  - pip
  - pip:
      - chardet == 4.0.0
      - urllib3 == 1.26.6
      - pandas == 1.3.2
      - openpyxl == 3.0.7
      - plotly == 5.3.1
      - kaleido == 0.2.1.post1
